# Generated by Django 2.1 on 2018-08-22 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180822_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User', to='boards.Entity'),
        ),
    ]
